from .parotid_left_2d_loader import ParotidLeft2DLoader
from .parotid_left_2d_visual_loader import ParotidLeft2DVisualLoader
from .parotid_left_3d_loader import ParotidLeft3DLoader
from .parotid_left_3d_visual_loader import ParotidLeft3DVisualLoader
