from .parotid_left_2d_loader import ParotidLeft2DLoader
from .parotid_left_2d_visual_loader import ParotidLeft2DVisualLoader
from .parotid_left_3d_localiser_loader import ParotidLeft3DLocaliserLoader
from .parotid_left_3d_localiser_visual_loader import ParotidLeft3DLocaliserVisualLoader
from .parotid_left_3d_segmenter_loader import ParotidLeft3DSegmenterLoader
from .parotid_left_3d_segmenter_visual_loader import ParotidLeft3DSegmenterVisualLoader
