#! /usr/bin/env bash

BOTTLENECK=8
DATASETS="['CIRCLES']"
MODEL_NAME="auto-encoder-circles"
NUM_EPOCHS=400
NUM_GPUS=0
NUM_NODES=1
NUM_WORKERS=4
NUM_SUBSET=None
RESUME=False
RESUME_CHECKPOINT=None
RUN_NAME="test"
SCRIPT_DIR="/data/gpfs/projects/punim1413/medical-imaging/scripts"
USE_LOGGER=False

python $SCRIPT_DIR/train/auto_encoder --slurm_job_id $SLURM_JOB_ID --model_name $MODEL_NAME --run_name $RUN_NAME --datasets $DATASETS --bottleneck $BOTTLENECK \
    --num_epochs $NUM_EPOCHS --num_gpus $NUM_GPUS --num_nodes $NUM_NODES --num_subset $NUM_SUBSET --num_workers $NUM_WORKERS --region $REGION --resume $RESUME \
    --resume_checkpoint $RESUME_CHECKPOINT --use_logger $USE_LOGGER
