#! /usr/bin/env bash

DATASETS="['PMCC-HN-TEST-SEG','PMCC-HN-TRAIN-SEG']"
REGION="BrainStem"
MODEL_NAME="segmenter-$REGION"
n_EPOCHS=5
N_FOLDS=5
n_GPUS=1
n_NODES=1
n_WORKERS=4
N_TRAIN=5
PRETRAINED_MODEL=None
RESUME=False
RESUME_CHECKPOINT=None
RUN_NAME="clinical-fold-4-samples-5-test-lr-schedule"
SCRIPT_DIR="/data/gpfs/projects/punim1413/medical-imaging/scripts"
TEST_FOLD=4
USE_LOGGER=True

python $SCRIPT_DIR/train/segmenter/segmenter \
    --datasets $DATASETS \
    --model_name $MODEL_NAME \
    --n_epochs $n_EPOCHS \
    --n_folds $N_FOLDS \
    --n_gpus $n_GPUS \
    --n_nodes $n_NODES \
    --n_train $N_TRAIN \
    --n_workers $n_WORKERS \
    --pretrained_model $PRETRAINED_MODEL \
    --use_logger $USE_LOGGER \
    --region $REGION \
    --resume $RESUME \
    --resume_checkpoint $RESUME_CHECKPOINT \
    --run_name $RUN_NAME \
    --slurm_array_job_id $SLURM_ARRAY_JOB_ID \
    --slurm_array_task_id $SLURM_ARRAY_TASK_ID \
    --test_fold $TEST_FOLD
