#! /usr/bin/env bash

DATASETS="['PMCC-HN-TEST-SEG','PMCC-HN-TRAIN-SEG']"
REGION="BrainStem"
MODEL_NAME="segmenter-$REGION"
NUM_EPOCHS=5
NUM_FOLDS=5
NUM_GPUS=1
NUM_NODES=1
NUM_WORKERS=4
NUM_TRAIN=5
PRETRAINED_MODEL=None
RESUME=False
RESUME_CHECKPOINT=None
RUN_NAME="clinical-fold-4-samples-5-test-lr-schedule"
SCRIPT_DIR="/data/gpfs/projects/punim1413/medical-imaging/scripts"
TEST_FOLD=4
USE_LOGGER=True

python $SCRIPT_DIR/train/segmenter/segmenter \
    --datasets $DATASETS \
    --model_name $MODEL_NAME \
    --num_epochs $NUM_EPOCHS \
    --num_folds $NUM_FOLDS \
    --num_gpus $NUM_GPUS \
    --num_nodes $NUM_NODES \
    --num_train $NUM_TRAIN \
    --num_workers $NUM_WORKERS \
    --pretrained_model $PRETRAINED_MODEL \
    --use_logger $USE_LOGGER \
    --region $REGION \
    --resume $RESUME \
    --resume_checkpoint $RESUME_CHECKPOINT \
    --run_name $RUN_NAME \
    --slurm_array_job_id $SLURM_ARRAY_JOB_ID \
    --slurm_array_task_id $SLURM_ARRAY_TASK_ID \
    --test_fold $TEST_FOLD
