DICOM_DATE_FORMAT = '%Y%m%d'
DICOM_RTDOSE_REF_RTPLAN_KEY = 'RefRTPLANSOPInstanceUID'
DICOM_RTPLAN_REF_RTSTRUCT_KEY = 'RefRTSTRUCTSOPInstanceUID'
DICOM_RTSTRUCT_REF_CT_KEY = 'RefCTSeriesInstanceUID'
DICOM_TIME_FORMAT = '%H%M%S'
TOLERANCE_MM = 1e-6
