#!/bin/bash
#SBATCH --nodes 1
#SBATCH --partition gpgpu
#SBATCH --mem 32G
#SBATCH --gres gpu:p100:1
#SBATCH --cpus-per-gpu 4
#SBATCH --time 0-1:00:00
#SBATCH -A punim1413
#SBATCH -q gpgpumse

module load gcccore/8.3.0
module load python/3.8.2
module load web_proxy

version=$(python --version)
echo $version

REGIONS=(
    'BrachialPlexus_L'
    'BrachialPlexus_R'
    'Brain'
    'BrainStem'
    'Cochlea_L'
    'Cochlea_R'
    'Lens_L'
    'Lens_R'
    'Mandible'
    'OpticNerve_L'
    'OpticNerve_R'
    'OralCavity'
    'Parotid_L'
    'Parotid_R'
    'SpinalCord'
    'Submandibular_L'
    'Submandibular_R'
)
RUNS=(
    'public-dilated-400epochs' # BrachialPlexus_L
    'public-dilated-400epochs' # BrachialPlexus_R
    'public-400epochs' # Brain
    'public-400epochs' # BrainStem
    'public-dilated-400epochs' # Cochlea_L
    'public-dilated-400epochs' # Cochlea_R
    'public-dilated-400epochs' # Lens_L
    'public-dilated-400epochs' # Lens_R
    'public-400epochs' # Mandible
    'public-dilated-400epochs' # OpticNerve_L
    'public-dilated-400epochs' # OpticNerve_R
    'public-400epochs' # OralCavity
    'public-400epochs' # Parotid_L
    'public-400epochs' # Parotid_R
    'public-400epochs' # SpinalCord
    'public-400epochs' # Submandibular_L
    'public-400epochs' # Submandibular_R
)
CHECKPOINTS=(
    'BEST' # BrachialPlexus_L
    'BEST' # BrachialPlexus_R
    'BEST' # Brain
    'BEST' # BrainStem
    'BEST' # Cochlea_L
    'BEST' # Cochlea_R
    'BEST' # Lens_L
    'BEST' # Lens_R
    'BEST' # Mandible
    'BEST' # OpticNerve_L
    'BEST' # OpticNerve_R
    'BEST' # OralCavity
    'BEST' # Parotid_L
    'BEST' # Parotid_R
    'BEST' # SpinalCord
    'BEST' # Submandibular_L
    'BEST' # Submandibular_R
)
CHECKPOINT=${CHECKPOINTS[$SLURM_ARRAY_TASK_ID]}
DATASET="PMCC-HN-TEST"
LOCALISER_SIZE="(128,128,96)"
LOCALISER_SPACING="(4,4,6.625)"
REGION=${REGIONS[$SLURM_ARRAY_TASK_ID]}
RUN=${RUNS[$SLURM_ARRAY_TASK_ID]}
SCRIPT_DIR="/data/gpfs/projects/punim1413/medical-imaging/scripts"
LOCALISER="('localiser-$REGION','$RUN','$CHECKPOINT')"

python $SCRIPT_DIR/predict/nifti/localiser/create_predictions --dataset $DATASET --localiser $LOCALISER --loc_size $LOCALISER_SIZE --loc_spacing $LOCALISER_SPACING --region $REGION
