#!/bin/bash
#SBATCH --nodes 1
#SBATCH --partition gpgpu
#SBATCH --mem 64G
#SBATCH --gres gpu:p100:1
#SBATCH --cpus-per-gpu 4
#SBATCH --time 2-0:00:00
#SBATCH -A punim1413
#SBATCH -q gpgpumse

module load gcccore/8.3.0
module load python/3.8.2
module load web_proxy

version=$(python --version)
echo $version

DATASETS="['PMCC-HN-TEST-SEG','PMCC-HN-TRAIN-SEG']"
REGIONS=(
    'BrachialPlexus_L'  # 0
    'BrachialPlexus_R'  # 1
    'Brain'             # 2
    'BrainStem'         # 3
    'Cochlea_L'         # 4
    'Cochlea_R'         # 5
    'Lens_L'            # 6
    'Lens_R'            # 7
    'Mandible'          # 8
    'OpticNerve_L'      # 9
    'OpticNerve_R'      # 10
    'OralCavity'        # 11
    'Parotid_L'         # 12
    'Parotid_R'         # 13
    'SpinalCord'        # 14
    'Submandibular_L'   # 15
    'Submandibular_R'   # 16
)
REGION=${REGIONS[$SLURM_ARRAY_TASK_ID]}
MODEL_NAME="segmenter-${REGION}"
# MODEL="clinical"
NUM_EPOCHS=450
NUM_FOLDS=5
NUM_GPUS=1
NUM_NODES=1
# NUM_TRAIN=5
NUM_WORKERS=4
# RESUME=False
if [ "$MODEL" = "public" ]; then
    RESUME_RUN="public-1gpu-150epochs-300epochs"
else
    RESUME_RUN="$MODEL-fold-$TEST_FOLD-samples-$NUM_TRAIN-300epochs"
fi
RESUME_CKPT='last'
SCRIPT_DIR="/data/gpfs/projects/punim1413/medical-imaging/scripts"
# TEST_FOLD=0
if [ "$MODEL" = "public" ]; then
    RUN_NAME="public-1gpu-450epochs"
else
    RUN_NAME="$MODEL-fold-$TEST_FOLD-samples-$NUM_TRAIN-450epochs"
fi
if [ "$MODEL" = "transfer" ]; then
    PRETRAINED_MODEL="('segmenter-$REGION','public-1gpu-150epochs','BEST')"
else
    PRETRAINED_MODEL=None
fi
USE_LOGGER=True

python $SCRIPT_DIR/train/segmenter/train.py \
    --datasets $DATASETS \
    --model_name $MODEL_NAME \
    --num_epochs $NUM_EPOCHS \
    --num_folds $NUM_FOLDS \
    --num_gpus $NUM_GPUS \
    --num_nodes $NUM_NODES \
    --num_train $NUM_TRAIN \
    --num_workers $NUM_WORKERS \
    --pretrained_model $PRETRAINED_MODEL \
    --use_logger $USE_LOGGER \
    --region $REGION \
    --resume $RESUME \
    --resume_run $RESUME_RUN \
    --resume_ckpt $RESUME_CKPT \
    --run_name $RUN_NAME \
    --slurm_array_job_id $SLURM_ARRAY_JOB_ID \
    --slurm_array_task_id $SLURM_ARRAY_TASK_ID \
    --test_fold $TEST_FOLD
