#! /usr/bin/env bash

parent_path=$( cd "$(dirname "${BASH_SOURCE[0]}")"; cd ..; pwd -P )
cd $parent_path

DATASET="PMCC-HN-TEST"
REGIONS=(
    # 'BrachialPlexus_L'
    # 'BrachialPlexus_R'
    'Brain'
    # 'BrainStem'
    # 'Cochlea_L'
    'Cochlea_R'
    'Lens_L'
    # 'Lens_R'
    # 'Mandible'
    # 'OpticNerve_L'
    # 'OpticNerve_R'
    'OralCavity'
    # 'Parotid_L'
    # 'Parotid_R'
    # 'SpinalCord'
    # 'Submandibular_L'
    # 'Submandibular_R'
)
LOCALISERS=()
for i in "${!REGIONS[@]}"; do
    localiser="('localiser-${REGIONS[i]}','public-large-400epochs','BEST')"
    LOCALISERS+=($localiser)
done

# Convert to string.
REGIONS=$(IFS=$','; echo "${REGIONS[*]}")
LOCALISERS=$(IFS=$','; echo "${LOCALISERS[*]}")

python localiser_figures --dataset $DATASET --regions $REGIONS --localisers $LOCALISERS

