import numpy as np
import pandas as pd
import pydicom as dcm
import torch
from typing import *

Axis = Literal[0, 1, 2]
AxisName = Literal['sagittal', 'coronal', 'axial']
Pixel = Tuple[int, int]               # Required by 'Box'.
Pixels = np.ndarray
Voxel = Tuple[int, int, int]          # Required by 'Box'.
Voxels = np.ndarray
Point2D = Tuple[float, float]         # Required by 'Box'.
Point3D = Tuple[float, float, float]  # Required by 'Box'.
PixelBox = Tuple[Pixel, Pixel]
VoxelBox = Tuple[Voxel, Voxel]
Point2DBox = Tuple[Point2D, Point2D]
Point3DBox = Tuple[Point3D, Point3D]
Points2D = np.ndarray
Points3D = np.ndarray
Channel = int
Channels = Union[Channel, List[Channel], Literal['all']]
Colour = Union[str, Tuple[float, float, float]]
DicomModality = Literal['ct', 'mr', 'rtdose', 'rtplan', 'rtstruct']
DicomSOPInstanceUID = str
Data = Union[np.ndarray, torch.Tensor]
ImageData = Data
ImageData2D = ImageData      # E.g. CT slices.
ImageData3D = ImageData      # E.g. CT/MR volumes.
CtDicom = dcm.dataset.FileDataset
CtData = ImageData3D
CtDatas = Union[CtData, List[CtData]]
CtSliceImage = ImageData2D
DoseData = ImageData3D
DoseDatas = Union[DoseData, List[DoseData]]
Extrema = Literal[0, 1]
FOV2D = Tuple[float, float]
FOV3D = Tuple[float, float, float]
GroupID = Union[int, float, str]
GroupIDs = Union[GroupID, List[GroupID]]
ImagesData = Union[ImageData, List[ImageData]]
LabelData = ImageData
LabelData3D = LabelData
Landmark = str 
LandmarkID = str
LandmarkData = pd.Series
Landmarks = Union[Landmark, List[Landmark], Literal['all']]
LandmarkIDs = Union[LandmarkID, List[LandmarkID], Literal['all']]
LandmarksData = pd.DataFrame
LandmarksVoxelData = pd.DataFrame
ModelCheckpoint = Union[str, Literal['best', 'last']]
ModelName = Tuple[str, str]
MrData = ImageData
NiftiModality = Literal['ct', 'dose', 'mr', 'regions']
NrrdModality = NiftiModality
Number = Union[int, float]
PatientID = str
PatientIDs = Union[PatientID, List[PatientID], Literal['all']]
Region = str
RegionID = str
Regions = Union[Region, List[Region], Literal['all']]
RegionIDs = Union[RegionID, List[RegionID], Literal['all']]
RegionData = LabelData3D
RegionsData = Dict[Region, RegionData]
RtDoseDicom = dcm.dataset.FileDataset
RtPlanDicom = dcm.dataset.FileDataset
RtStructDicom = dcm.dataset.FileDataset
SampleID = int
SampleIDs = Union[SampleID, List[SampleID], Literal['all']]
SeriesID = str
SeriesIDs = Union[SeriesID, List[SeriesID], Literal['all']]
Size2D = Tuple[int, int]
Size3D = Tuple[int, int, int]
Spacing2D = Tuple[float, float]
Spacing3D = Tuple[float, float, float]
Split = Literal['train', 'validation', 'test']
Splits = Union[Split, List[Split], Literal['all']]
SpartanPartition = Literal['feit-gpu-a100', 'gpu-a100', 'gpu-a100-short', 'gpu-h100', 'sapphire']
SpartanPartitions = Union[SpartanPartition, List[SpartanPartition]]
StudyID = str
StudyIDs = Union[StudyID, List[StudyID], Literal['all']]
TrainingInterval = str
VectorData = Data
VectorsData = Union[VectorData, List[VectorData]]
