#! /usr/bin/env bash

parent_path=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
cd $parent_path

python localiser --model_name localiser-pr --run_name baseline --dataset PMCC-HN-TRAIN-LOC --num_gpus 1 --num_nodes 1 --num_workers 8 --regions Parotid_R --use_logger True
