#! /usr/bin/env bash

parent_path=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
cd $parent_path

python localiser --dataset PMCC-HN-TRAIN-LOC --run_name baseline --num_gpus 1 --num_nodes 1 --num_workers 1
