#!/usr/bin/env python
import fire
import os
import sys

root_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
sys.path.append(root_dir)

from mymi.training import train_segmenter_2d

if __name__ == '__main__':
    fire.Fire(train_segmenter_2d)

# Sample args:
# --datasets "['CIRCLES']" --num_gpus 4 --num_nodes 1 --num_workers 4 --use_logger True
