#! /usr/bin/env bash

parent_path=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
cd $parent_path

python dicom --dataset HN1 --dest_dataset HN1-LOC --p_test 0 --p_train 0.8 --p_val 0.2 \
    --regions Parotid_L --size '(128, 128, 96)' --spacing '(4, 4, 6.625)'
