#! /usr/bin/env bash

REGIONS="('Parotid_L','Parotid_R')"

parent_path=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
cd $parent_path

python dicom --dataset HNSCC --dest_dataset HNSCC-SEG --p_test 0 --p_train 0.8 --p_val 0.2 \
    --regions $REGIONS --spacing '(1, 1, 2)'
