#! /usr/bin/env python
import os
import sys

root_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
sys.path.append(root_dir)

from mymi.dataset.raw.dicom import process_dicom

ds = 'HNSCC'
regions = ['Parotid_L', 'Parotid_R']
process_dicom(ds, regions=regions)
