#! /usr/bin/env python
import os
import sys

root_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
sys.path.append(root_dir)

from mymi.dataset.raw.nifti import process_nifti

ds = 'PMCC-HN-TRAIN'
regions = ['Parotid_L', 'Parotid_R']
spacing = (1, 1, 3)
process_nifti(ds, spacing=spacing)
