#! /usr/bin/env bash

parent_path=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
cd $parent_path

python nifti --dataset PMCC-HN-TRAIN-FLIP --dest_dataset PMCC-HN-TRAIN-FLIP-SEG --p_test 0 --p_train 0.8 --p_val 0.2 \
    --spacing '(1, 1, 2)'
