#! /usr/bin/env bash

parent_path=$( cd "$(dirname "${BASH_SOURCE[0]}")"; cd ..; pwd -P )
cd $parent_path

DATASET="CIRCLES"
NUM_SAMPLES=500
SIZE="(128,128)"

python generate_circles --dataset $DATASET --size $SIZE --num_samples $NUM_SAMPLES
