#!/bin/bash
#SBATCH --nodes 1
#SBATCH --partition physical
#SBATCH --mem 32G
#SBATCH --time 0-1:00:00
#SBATCH -A punim1413

module load gcccore/8.3.0
module load python/3.8.2
module load web_proxy

version=$(python --version)
echo $version

REGIONS=(
    'BrachialPlexus_L'
    'BrachialPlexus_R'
    'Brain'
    'BrainStem'
    'Cochlea_L'
    'Cochlea_R'
    'Lens_L'
    'Lens_R'
    'Mandible'
    'OpticNerve_L'
    'OpticNerve_R'
    'OralCavity'
    'Parotid_L'
    'Parotid_R'
    'SpinalCord'
    'Submandibular_L'
    'Submandibular_R'
)
RUNS=(
    'public-large-400epochs' # BrachialPlexus_L
    'public-large-400epochs' # BrachialPlexus_R
    'public-400epochs' # Brain
    'public-400epochs' # BrainStem
    'public-dilated-400epochs' # Cochlea_L
    'public-dilated-400epochs' # Cochlea_R
    'public-dilated-400epochs' # Lens_L
    'public-dilated-400epochs' # Lens_R
    'public-400epochs' # Mandible
    'public-dilated-400epochs' # OpticNerve_L
    'public-dilated-400epochs' # OpticNerve_R
    'public-400epochs' # OralCavity
    'public-400epochs' # Parotid_L
    'public-400epochs' # Parotid_R
    'public-400epochs' # SpinalCord
    'public-400epochs' # Submandibular_L
    'public-400epochs' # Submandibular_R
)
CHECKPOINT='BEST'
DATASET="PMCC-HN-TEST"
REGION=${REGIONS[$SLURM_ARRAY_TASK_ID]}
RUN=${RUNS[$SLURM_ARRAY_TASK_ID]}
LOCALISER="('localiser-$REGION','$RUN','$CHECKPOINT')"
SCRIPT_DIR="/data/gpfs/projects/punim1413/medical-imaging/scripts"

python $SCRIPT_DIR/evaluate/nifti/localiser/create_evaluation --dataset $DATASET --region $REGION --localiser $LOCALISER
