#!/bin/bash
#SBATCH --nodes 1
#SBATCH --partition physical
#SBATCH --mem 32G
#SBATCH --time 0-1:00:00
#SBATCH -A punim1413

module load gcccore/8.3.0
module load python/3.8.2
module load web_proxy

version=$(python --version)
echo $version

REGIONS=(
    'BrachialPlexus_L'
    'BrachialPlexus_R'
    'Brain'
    'BrainStem'
    'Cochlea_L'
    'Cochlea_R'
    'Lens_L'
    'Lens_R'
    'Mandible'
    'OpticNerve_L'
    'OpticNerve_R'
    'OralCavity'
    'Parotid_L'
    'Parotid_R'
    'SpinalCord'
    'Submandibular_L'
    'Submandibular_R'
)
RUNS=(
    'public-dilated-400epochs' # BrachialPlexus_L
    'public-dilated-400epochs' # BrachialPlexus_R
    'public-400epochs' # Brain
    'public-400epochs' # BrainStem
    'public-dilated-400epochs' # Cochlea_L
    'public-dilated-400epochs' # Cochlea_R
    'public-dilated-400epochs' # Lens_L
    'public-dilated-400epochs' # Lens_R
    'public-400epochs' # Mandible
    'public-dilated-400epochs' # OpticNerve_L
    'public-dilated-400epochs' # OpticNerve_R
    'public-400epochs' # OralCavity
    'public-400epochs' # Parotid_L
    'public-400epochs' # Parotid_R
    'public-400epochs' # SpinalCord
    'public-400epochs' # Submandibular_L
    'public-400epochs' # Submandibular_R
)
CHECKPOINTS=(
    'BEST' # BrachialPlexus_L
    'BEST' # BrachialPlexus_R
    'BEST' # Brain
    'BEST' # BrainStem
    'BEST' # Cochlea_L
    'BEST' # Cochlea_R
    'BEST' # Lens_L
    'BEST' # Lens_R
    'BEST' # Mandible
    'BEST' # OpticNerve_L
    'BEST' # OpticNerve_R
    'BEST' # OralCavity
    'BEST' # Parotid_L
    'BEST' # Parotid_R
    'BEST' # SpinalCord
    'BEST' # Submandibular_L
    'BEST' # Submandibular_R
)
PATCH_SIZES=(
    '(200,115,70)' # 'BrachialPlexus_L'
    '(200,115,70)' # 'BrachialPlexus_R'
    '(170,205,90)' # 'Brain'
    '(95,85,60)' # 'BrainStem'
    '(70,65,25)' # 'Cochlea_L'
    '(70,65,25)' # 'Cochlea_R'
    '(55,50,25)' # 'Lens_L'
    '(55,50,25)' # 'Lens_R'
    '(180,170,75)' # 'Mandible'
    '(70,90,30)' # 'OpticNerve_L'
    '(70,90,30)' # 'OpticNerve_R'
    '(180,160,155)' # 'OralCavity'
    '(95,120,60)' # 'Parotid_L'
    '(95,120,60)' # 'Parotid_R'
    '(80,180,190)' # 'SpinalCord'
    '(75,85,50)' # 'Submandibular_L'
    '(75,85,50)' # 'Submandibular_R'
)
CHECKPOINT=${CHECKPOINTS[$SLURM_ARRAY_TASK_ID]}
DATASET="PMCC-HN-TEST"
PATCH_SIZE=${PATCH_SIZES[$SLURM_ARRAY_TASK_ID]}
REGION=${REGIONS[$SLURM_ARRAY_TASK_ID]}
RUN=${RUNS[$SLURM_ARRAY_TASK_ID]}
LOCALISER="('localiser-$REGION','$RUN','$CHECKPOINT')"
SCRIPT_DIR="/data/gpfs/projects/punim1413/medical-imaging/scripts"

python $SCRIPT_DIR/evaluate/nifti/localiser/create_evaluation --dataset $DATASET --region $REGION --localiser $LOCALISER --patch_size $PATCH_SIZE
