#!/bin/bash
#SBATCH --account punim1413
#SBATCH --partition sapphire
#SBATCH --nodes 1
#SBATCH --mem 64G
#SBATCH --time 0-06:00:00
##SBATCH --test-only

module load GCCcore/11.3.0
module load Python/3.10.4
source ~/venvs/medical-imaging/bin/activate

version=$(python --version)
echo $version

nnUNetv2_plan_and_preprocess \
    -d $DATASET_ID \
    -pl nnUNetPlannerResEncXL \
    --verify_dataset_integrity \
