#!/usr/bin/env python
import fire
import os
import sys
import torch

root_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
sys.path.append(root_dir)

from mymi import config
from mymi.models import replace_ckpt_alias

def print_epoch(
    model: str,
    run: str,
    ckpt: str = 'last') -> None:
    # Get number of epochs.
    model = replace_ckpt_alias((model, run, ckpt))
    filepath = os.path.join(config.directories.models, *model[:2], f'{model[2]}.ckpt')
    state = torch.load(filepath, map_location=torch.device('cpu'))
    n_epochs = state['epoch'] + 1       # Starts at 0.

    print(f"""
Model: {model}
Num. Epochs: {n_epochs}
""")

fire.Fire(print_epoch)
