#! /usr/bin/env bash

parent_path=$( cd "$(dirname "${BASH_SOURCE[0]}")"; cd ..; pwd -P )
cd $parent_path

DATASET="OPC"
DEST_DATASET="OPC-SEG"
P_TRAIN=0.8
P_VAL=0.2
P_TEST=0
REGIONS="('BrachialPlexus_L','BrachialPlexus_R','Brain','BrainStem','Lens_L','Lens_R','Mandible','Neck_L','Neck_R','OpticChiasm','OpticNerve_L','OpticNerve_R','Parotid_L','Parotid_R','SpinalCord','Submandibular_L','Submandibular_R')"
SIZE=None
SPACING="(1,1,2)"

python process_dicom --dataset $DATASET --dest_dataset $DEST_DATASET --p_train $P_TRAIN --p_val $P_VAL --p_test $P_TEST \
    --regions $REGIONS --size $SIZE --spacing $SPACING
