#! /usr/bin/env python
from distutils.dir_util import copy_tree
import os
import pandas as pd
import shutil
from tqdm import tqdm
import sys

root_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..'))
sys.path.append(root_dir)

from mymi.dataset.raw import recreate
from mymi import logging

DATASET_PATH = os.path.join('H:\\', 'data', 'mymi', 'datasets', 'raw')
DRY_RUN = False
FILENAME_NUM_DIGITS = 5
REGIONS = ['BrachialPlexus_L', 'BrachialPlexus_R', 'Brain', 'BrainStem', 'Cochlea_L', 'Cochlea_R',
    'Eye_L', 'Eye_R', 'Larynx', 'Lens_L', 'Lens_R', 'Mandible', 'Oesophagus', 'OpticNerve_L', 'OpticNerve_R',
    'OralCavity', 'Parotid_L', 'Parotid_R', 'PharynConst', 'SpinalCanal', 'SpinalCord', 'Submandibular_L',
    'Submandibular_R']

# Copy dataset.
old_ds_path = os.path.join(DATASET_PATH, 'PMCC-HN-TRAIN-sensitive')
new_ds_path = os.path.join(DATASET_PATH, 'PMCC-HN-TRAIN')
logging.info('Copying dataset...')
copy_tree(old_ds_path, new_ds_path)
logging.info('Copied.')

# Create CT map.
ct_path = os.path.join(new_ds_path, 'ct')
ct_files = list(sorted(os.listdir(ct_path)))
ct_ids = list(f.replace('.nii.gz', '') for f in ct_files)
map_df = pd.DataFrame(ct_ids, columns=['series_id'])

# Save map.
filepath = os.path.join(old_ds_path, 'map.csv')
map_df.to_csv(filepath)

for anon_id, row in tqdm(map_df.iterrows()):
    # Rename CT files.
    old_filename = f"{row[0]:0{FILENAME_NUM_DIGITS}}.nii.gz"
    old_filepath = os.path.join(old_ds_path, 'ct', old_filename)
    new_filename = f"{anon_id:0{FILENAME_NUM_DIGITS}}.nii.gz"
    new_filepath = os.path.join(old_ds_path, 'ct', new_filename)
    if DRY_RUN:
        print(f"Moving from '{old_filepath}' to '{new_filepath}'.")
    else:
        shutil.move(old_filepath, new_filepath)

    # Rename region files.
    for region in REGIONS:
        old_filename = f"{row[0]:0{FILENAME_NUM_DIGITS}}.nii.gz"
        old_filepath = os.path.join(old_ds_path, region, old_filename)
        new_filename = f"{anon_id:0{FILENAME_NUM_DIGITS}}.nii.gz"
        new_filepath = os.path.join(old_ds_path, region, new_filename)
        if os.path.exists(old_filepath):
            if DRY_RUN:
                print(f"Moving from '{old_filepath}' to '{new_filepath}'.")
            else:
                shutil.move(old_filepath, new_filepath)
