#! /usr/bin/env python
import numpy as np
import os
import sys
from tqdm import tqdm

root_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..'))
sys.path.append(root_dir)

from mymi import dataset
from mymi import logging

# Load seg dataset.
seg_ds_name = 'PMCC-HN-TRAIN-SEG'
seg_ds = dataset.get(seg_ds_name, 'processed')

# Load raw dataset.
raw_ds = 'PMCC-HN-TRAIN'
raw_ds = dataset.get(raw_ds)

# Load manifest.
manifest = seg_ds.manifest()
manifest['spacing'] = ''

for i, row in tqdm(manifest.iterrows()):
    # Look up spacing.
    spacing = raw_ds.patient(row['patient-id']).ct_spacing()

    # Add to manifest.
    manifest.at[i, 'spacing'] = str(spacing)

    # Remove patient ID.
    manifest.at[i, 'patient-id'] = np.nan

# Save manifest.
filename = 'spacing-manifest.csv'
filepath = os.path.join(seg_ds._path, filename)
manifest.to_csv(filepath)
