#! /usr/bin/env python
import os
import sys
from tqdm import tqdm

root_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..'))
sys.path.append(root_dir)

from mymi import dataset as ds

dry_run = True
dataset = 'PMCC-HN-TRAIN'

set = ds.get(dataset, 'nifti')
pats = set.list_patients()

for pat in tqdm(pats):
    # Load labels.
    data = set.patient(pat).region_data()
    for n, d in data.items():
        if d.sum() == 0:
            print(f"Empty label - pat:{pat},region:{n}")
