#! /usr/bin/env bash

parent_path=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; cd ..; pwd -P )
cd $parent_path

DATASETS="['PMCC-HN-TEST-LOC','PMCC-HN-TRAIN-LOC']"

python test_loader_manifest --datasets $DATASETS --regions 'all' --num_folds 5 --test_fold 0

