#! /usr/bin/env bash

parent_path=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; cd ..; pwd -P )
cd $parent_path

DATASET="PMCC-HN-TRAIN-LOC"

python test_loader_manifest --dataset $DATASET --regions 'all' --num_folds 5 --test_fold 0

