#! /usr/bin/env python3
import argparse
import os
import sys
import torch

root_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
sys.path.append(root_dir)

from mymi import dataset
from mymi.dataset import DicomDataset
from mymi import logging
from mymi.metrics import batch_dice
from mymi import utils

# Parse args.
parser = argparse.ArgumentParser(description='Compare contours to ground truth')
parser.add_argument('-e', '--evaluate', action='store', help='the evaluation dataset', required=True)
parser.add_argument('-g', '--ground-truth', action='store', help='the ground truth dataset', required=True)
parser.add_argument('-l', '--log-level', action='store', default='info', help='sets the log level')
args = parser.parse_args()

# Create logger.
logging.config(args.log_level)

# Create ground truth dataset.
gt_ds = DicomDataset(args.ground_truth)

# Load evaluation patients.
eval_ds = DicomDataset(args.evaluate, ct_from=args.ground_truth)
pats = eval_ds.list_patients()
print(pats)

# Label names.
gt_labels = 'Parotid_L'
eval_labels = 'Parotid_L'

# TODO: Handle different contours names, e.g. Parotid-Left vs Parotid_L.
# Map from database to our local names.

# Add metrics for patients.
dice_scores = []
for pat in pats:
    print(pat)
    # Load ground truth.
    _, gt_data = gt_ds.patient(pat).label_data(labels=gt_labels)[0]

    # Load evaluation data.
    _, eval_data = eval_ds.patient(pat).label_data(labels=eval_labels)[0]

    # Calculate DSC.
    gt_data = torch.Tensor(gt_data).unsqueeze(0)
    eval_data = torch.Tensor(eval_data).unsqueeze(0)

    dsc = batch_dice(gt_data, eval_data)  

    print(dsc)

