#! /usr/bin/env bash

parent_path=$( cd "$(dirname "${BASH_SOURCE[0]}")"; cd ..; pwd -P )
cd $parent_path

DATASET="PMCC-HN-TEST"
LOCALISER_SIZE="(128,128,150)"
LOCALISER_SPACING="(4,4,4)"
REGIONS=(
    # 'BrachialPlexus_L'
    # 'BrachialPlexus_R'
    'Brain'
    # 'BrainStem'
    # 'Cochlea_L'
    'Cochlea_R'
    'Lens_L'
    # 'Lens_R'
    # 'Mandible'
    # 'OpticNerve_L'
    # 'OpticNerve_R'
    'OralCavity'
    # 'Parotid_L'
    # 'Parotid_R'
    # 'SpinalCord'
    # 'Submandibular_L'
    # 'Submandibular_R'
)
RUN="public-large-400epochs"

for i in "${!REGIONS[@]}"; do
    localiser="('localiser-${REGIONS[i]}','$RUN','BEST')"
    python create_evaluation --dataset $DATASET --localiser $localiser --region ${REGIONS[i]}
done
