#! /usr/bin/env bash

parent_path=$( cd "$(dirname "${BASH_SOURCE[0]}")"; cd ..; pwd -P )
cd $parent_path

DATASET="OPC"
REGIONS="('BrachialPlexus_L','BrachialPlexus_R','Brain','BrainStem','Lens_L','Lens_R','Mandible','Neck_L','Neck_R','OpticNerve_L','OpticNerve_R','Parotid_L','Parotid_R','SpinalCord','Submandibular_L','Submandibular_R')"
ANONYMISE=False

python convert_to_nifti --dataset $DATASET --regions $REGIONS --anonymise $ANONYMISE
