#! /usr/bin/env bash

parent_path=$( cd "$(dirname "${BASH_SOURCE[0]}")"; cd ..; pwd -P )
cd $parent_path

DATASET="TEST"
REGIONS="('Parotid_L','Parotid_R')"
ANONYMISE=False

python convert_to_nifti --dataset TEST --regions $REGIONS --anonymise $ANONYMISE