#! /usr/bin/env bash

parent_path=$( cd "$(dirname "${BASH_SOURCE[0]}")"; cd .. ;pwd -P )
cd $parent_path

DATASET="PMCC-HN-TEST"
LOCALISER="('localiser-pl','baseline','epoch=182-step=39893')"
NAME="Parotid_L-baseline"
REGION='Parotid_L'
SEGMENTER="('segmenter-pl','baseline','epoch=188-step=41201')"

python evaluate_model --name $NAME --dataset $DATASET --localiser $LOCALISER --segmenter $SEGMENTER --region $REGION
