#!/bin/bash
#SBATCH --nodes 1
#SBATCH --partition gpgpu
#SBATCH --mem 32G
#SBATCH --gres gpu:p100:1
#SBATCH --cpus-per-gpu 4
#SBATCH --time 0-1:00:00
#SBATCH -A punim1413
#SBATCH -q gpgpumse

module load gcccore/8.3.0
module load python/3.8.2
module load web_proxy

version=$(python --version)
echo $version

REGIONS=(
    'BrachialPlexus_L'
    'BrachialPlexus_R'
    'Brain'
    'BrainStem'
    'Cochlea_L'
    'Cochlea_R'
    'Lens_L'
    'Lens_R'
    'Mandible'
    'OpticNerve_L'
    'OpticNerve_R'
    'OralCavity'
    'Parotid_L'
    'Parotid_R'
    'SpinalCord'
    'Submandibular_L'
    'Submandibular_R'
)
DATASET="PMCC-HN-TEST"
LOCALISER_SIZE="(128,128,150)"
LOCALISER_SPACING="(4,4,4)"
REGION=${REGIONS[$SLURM_ARRAY_TASK_ID]}
RUN='public-large-400epochs'
SCRIPT_DIR="/data/gpfs/projects/punim1413/medical-imaging/scripts"
LOCALISER="('localiser-$REGION','$RUN','BEST')"

python $SCRIPT_DIR/predict/nifti/localiser/create_predictions --dataset $DATASET --localiser $LOCALISER --loc_size $LOCALISER_SIZE --loc_spacing $LOCALISER_SPACING --region $REGION
