#! /usr/bin/env bash

parent_path=$( cd "$(dirname "${BASH_SOURCE[0]}")"; cd ..; pwd -P )
cd $parent_path

REGIONS=(
    # 'BrachialPlexus_L'  # 0
    # 'BrachialPlexus_R'  # 1
    'Brain'             # 2
    # 'BrainStem'         # 3
    # 'Cochlea_L'         # 4
    # 'Cochlea_R'         # 5
    # 'Lens_L'            # 6
    # 'Lens_R'            # 7
    # 'Mandible'          # 8
    # 'OpticNerve_L'      # 9
    # 'OpticNerve_R'      # 10
    # 'OralCavity'        # 11
    # 'Parotid_L'         # 12
    # 'Parotid_R'         # 13
    # 'SpinalCord'        # 14
    # 'Submandibular_L'   # 15
    # 'Submandibular_R'   # 16
)
LOCALISER_SIZE="(128,128,150)"
LOCALISER_SPACING="(4,4,4)"
NUM_FOLDS=5
SEGMENTER_SPACING="(1,1,2)"
TEST_FOLD=0

for i in "${!REGIONS[@]}"; do
    region=${REGIONS[i]}
    datasets="['PMCC-HN-TEST-$region-LOC','PMCC-HN-TRAIN-$region-LOC']"
    localiser="('localiser-$region','public-1gpu-100epochs','BEST')"
    segmenter="('segmenter-$region','public-1gpu-100epochs','BEST')"
    python create_predictions_from_loader --datasets $datasets --region ${REGIONS[i]} --localiser $localiser --loc_size $LOCALISER_SIZE --loc_spacing $LOCALISER_SPACING \
        --segmenter $segmenter --seg_spacing $SEGMENTER_SPACING --num_folds $NUM_FOLDS --test_fold $TEST_FOLD
done
